spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/community
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      session_factory:
        statement_inspector: package capstone.communityservice.global.common.filter.QueryInspector;
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug

# AWS S3
cloud:
  aws:
    s3:
      bucket: temp
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    key:
      access-key: temp
      secret-key: temp

# Actuator
management:
  server:
    port: 9292
  endpoints:
    web:
      exposure:
        include: "*"