spring:
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      voice-connection-state-event: "voiceConnectionStateEventTopic"
server:
  port: 5000
  ssl:
    enabled: false


OPENVIDU_URL: http://localhost:4443/
OPENVIDU_SECRET: MY_SECRET