name: NotificationService CI/CD

on:
  push:
    branches:
      - 'BE/dev'
    paths:
      - 'src/backend/notification-service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
          
      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.NOTIFICATION_ACTION_TOKEN }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x src/backend/notification-service/gradlew

      - name: Project Build
        env:
          jasypt.encryptor.password: ${{ secrets.JASYPT_PASSWORD }}
        working-directory: ./src/backend/notification-service
        run: ./gradlew clean build
        shell: bash

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Image Build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/notification-service:1.0 ./src/backend/notification-service

      - name: Docker Image Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/notification-service:1.0

      - name: GCP 인스턴스 접속 및 무중단 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd /script
            make notification-update

